language: node_js
node_js:
  - "0.12"
  - "4.3"

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

before_script:
  - npm run-script buildMochaOpts
  - npm install -g codeclimate-test-reporter

script:
  - npm run-script lint
  - npm test

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token: 6e7c24d48f0525d22c77506a9241e382273f9f2b20c3eecbce8219d8f28aee23
